# THIS DOCKERFILE IS INTENDED FOR DEVELOPMENT ENVIRONMENTS
# DO NOT USE THIS FOR PRODUCTION USAGES.

version: '3.8'

services:
  mariadb:
    image: bitnami/mariadb:10.9.3
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/bitnami/mariadb
      - ./dev:/docker-entrypoint-initdb.d
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=user
      - MARIADB_USER=nestjs
      - MARIADB_PASSWORD=password
    healthcheck:
      test: mysql --protocol=tcp -h mariadb -u root -e "show databases;"
      interval: 10s
      timeout: 5s
      retries: 5

  user-api-test:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./user-api:/app/
    environment:
      - DATABASE_HOST=mariadb
      - PORT=3000
      - DATABASE_USER=nestjs
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=test
      - JWT_SECRET=test
    depends_on:
      - mariadb
    command: npm run test:e2e

  user-api-prod:
    image: mohammaddocker/ms-course-user-api:0.0.5
    environment:
      - DATABASE_HOST=mariadb
      - PORT=3000
      - DATABASE_USER=root
      - DATABASE_NAME=user
      - JWT_SECRET=test
    depends_on:
      - mariadb
    ports:
      - 8080:3000
  product-api-prod:
    image: mohammaddocker/ms-course-product-api:0.0.4
    environment:
      - DATABASE_HOST=mariadb
      - PORT=3000
      - DATABASE_USER=root
      - DATABASE_NAME=product
      - JWT_SECRET=test
    depends_on:
      - mariadb
    ports:
      - 8081:3000

volumes:
  mariadb_data:
    driver: local