# THIS DOCKERFILE IS INTENDED FOR DEVELOPMENT ENVIRONMENTS
# DO NOT USE THIS FOR PRODUCTION USAGES.

version: '3.8'

services:
  mariadb:
    image: bitnami/mariadb:10.9.3
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/bitnami/mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=user
      - MARIADB_USER=nestjs
      - MARIADB_PASSWORD=password
    healthcheck:
      test: mysql --protocol=tcp -h mariadb -u root -e "show databases;"
      interval: 10s
      timeout: 5s
      retries: 5

  user-api:
    image: node:16
    working_dir: /app
    volumes:
      - /app/node_modules
      - ./user-api:/app/
    env_file:
      - ./user-api/.env.test
    environment:
      - DATABASE_HOST=mariadb
    stdin_open: true

volumes:
  mariadb_data:
    driver: local